### ISSUE TITLE
Master C++ (HPC and CUDA for Quant role)

### ISSUE THREAD

**Issue by MckinstryJ** [MckinstryJ/QuantResearchPTC#12]
- [x] Complete basic tutorial

- [ ] Work on weak topics

- [ ] Complete advanced tutorial

- [ ] Work on weak topics

- [ ] Build rasberry pi cluster

- [ ] C++ and HPC for distributed systems (RasPy)

- [ ] C++ and CUDA

- [ ] C++ and SQLite

- [ ] C++ books for Quants

- [ ] C++ and Software Engineering

- [ ] Translate Financial Math to C++

- [ ] MatLab code to C++

- [ ] C++ to Python code
